---
title: " git_00"
author: "Yessica Garay"
date: "02-21-2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!”  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


He halted in the wind, and - what was that  
Far in the maples, pale, but not a ghost?  
He stood there bringing March against his thought,  
And yet too ready to believe the most.  

"Oh, that's the Paradise-in-bloom," I said;  
And truly it was fair enough for flowers  
had we but in us to assume in march  
Such white luxuriance of May for ours.  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
    Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  




## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

When I consider everything that grows  
holds in perfection but a little moment,  
That this huge stage presenteth nought but shows  
Whereon the stars in secret influence comment;  
When I perceive that men as plants increase,  
Cheered and check'd even by the selfsame sky,  
Vaunt in their youthful sap, at height decrease,  
And wear their brave state out of memory;  
Then the conceit of this inconstant stay  
Sets you most rich in youth before my sight,  
Where wasteful Time debateth with Decay  
To change your day of youth to sullied night;  
And all in war with Time for love of you,  
As he takes from you, I engraft you new.  

